### ISSUE TITLE
Statikus analízis

### ISSUE THREAD

**Issue by daunera** [BME-MIT-IET/Hmmm-iet-2018#1]
Statikus alanízissel ellenőrizzük a test/url.js fájlt az alábbi javascript-es statikus analízis tool-okkal: jslint, jshint, eslint

**Comment by daunera** [comment]
A statikus analízishez létrehoztunk egy külön branch-et _static-analysis_ néven

**Comment by daunera** [comment]
Ezután @beke07-vel közösen ellenőriztük a jslint által jelzett problémákat és mindegyiket javítottuk, típusonként különböző kommitokban dade66c620c1af393fd44d838365edaa7bdd952c - dec5612b640e5be44498d694b42630ed16e12eec

**Comment by daunera** [comment]
@beke07 Még javított a test file-ban is fa8f7ec1f2a6ec219e7989c225652f51b5e4b385

**Comment by daunera** [comment]
A prjektet eredetileg is jshint-tel ellenőrzik, így egyetlen hibán kívül nem is kaptunk mást, ezt Tamás @beke07  javította fa8f7ec1f2a6ec219e7989c225652f51b5e4b385

**Comment by daunera** [comment]
eslint konfiguráció után jelzett hibáit javítottam 50676f4f1760c816831588fa7931d4767aa3bf47

**Comment by daunera** [comment]
Az eredeti hibákat jelző logokat feltöltöttem a wiki oldalhoz lehet hasznos bb52260cde4f00c739e164c47a5f7737ab04bff5 Ezen kívül szerintünk a javítások készen vannak, feladat review-ra javasuljuk

**Comment by daunera** [comment]
_Közben készül a wiki oldal is összegzésnek_

**Comment by benjamingehl** [comment]
@BMark96-al átnéztük és ellenőriztük a statikus analízishez tartozó pull requestet és mergeltük a master branch-be.
