### ISSUE TITLE
Manuális kód átvizsgálás

### ISSUE THREAD

**Issue by BMark96** [BME-MIT-IET/Hmmm-iet-2018#3]
Feladatok:
- Forrásfájlok átnézése és véleményezése (url.js és test/url.js)
- Pull request, majd merge
- Wiki oldal elkészítése

**Comment by benjamingehl** [comment]
Az átvizsgáláshoz/javításhoz létrehoztunk egy branch-et _manual-check_ néven

**Comment by BMark96** [comment]
Az olvashatóságot javítaná, ha a reguláris kifejezések külön változókba lennének szervezve, és kommentben röviden le lenne írva azok pontos jelentése.

**Comment by benjamingehl** [comment]
A kód alapvetően a régebbi stílusú JavaScript módszereket követi. (Nem mondjuk ECMAScript 2015 vagy újabb)
Sok helyen komplex, egymásba ágyazott vezérlési szerkezetek. Ezeket külön függvényekbe darabolással ki lehetne váltani.

**Comment by benjamingehl** [comment]
A stílushibákat javítottuk a _static-analysis_ Issue keretében.

**Comment by BMark96** [comment]
Változtatások az url.js fájlon (https://github.com/BME-MIT-IET/Hmmm-iet-2018/commit/beff7cdeefa5cb4c69323fad94fbf741abc23ea0, https://github.com/BME-MIT-IET/Hmmm-iet-2018/commit/6286696735f925dcb369dca897e3e34174a49266)
-

**Comment by BMark96** [comment]
A dokumentációt elkészítettük (@benjamingehl)

**Comment by BMark96** [comment]
A feladat véleményünk szerint elkészült, review-ra javasoljuk

**Comment by daunera** [comment]
Végignéztem az issueban említett tevékenységeket és okés, zárom :)
