### ISSUE TITLE
Unit tesztek

### ISSUE THREAD

**Issue by daunera** [BME-MIT-IET/Hmmm-iet-2018#5]

**Comment by daunera** [comment]
Felkonfiguráltam teljesen a mocha-t és az istambult. Az  npm run cover paranccsal végighívja az összes test/mappában lévő tesztesetet

**Comment by daunera** [comment]
Készítettem két unit tesztet, a queryLength() és az isEmptyQuery()-re

**Comment by daunera** [comment]
@beke07 -tal tartottunk egy kis eligazítást, hogy mikre írjunk, igyekeztünk figyelembe venni a kód lefedettséget is

**Comment by daunera** [comment]
@beke07 Kibővítette a unit teszteket, közel 10-15 esettel, így most már elég teljes a paletta

**Comment by BMark96** [comment]
@benjamingehl-lel leteszteltük, hogy ha böngészőben futtatjuk a kódot, akkor is létre tudunk-e hozni egy URL objektumot. Ehhez a Google Puppeteer nevű node könyvtárát használtuk fel

**Comment by daunera** [comment]
Kicsit módosítottunk a unit tesztek struktúráján, hogy az egy függvényhez vagy részhez tartozók egy descirbe-alá több it-kén tartozzanak a logika szamályai szerint :) Szerintünk megvan ez a rész, a kódlefedettséges csapatnak átadjuk a terepet.

**Comment by benjamingehl** [comment]
A unit tesztek elkészítése után a tesztesetek közel 100%-os lefedettséggel járják be a kódot, az Issue így elérte célját. Szép munka! Az Issue lezárva.
