### ISSUE TITLE
Kód lefedettség

### ISSUE THREAD

**Issue by daunera** [BME-MIT-IET/Hmmm-iet-2018#6]

**Comment by benjamingehl** [comment]
Code coverage Report: https://github.com/BME-MIT-IET/Hmmm-iet-2018/blob/unit-test/url.js#L51
Az adott sort a headess Chrome-al futtattuk, így a lefedettségi teszten nem lett kimutatva, de ez a sor is tesztelve lett.

**Comment by benjamingehl** [comment]
Code coverage Report: https://github.com/BME-MIT-IET/Hmmm-iet-2018/blob/unit-test/url.js#L82
A fenti sor egy platform specifikus elágazás. Egy platformon nem tudtunk elérni (az adott sorban) 100%-os lefedettséget, de a külön rendszereken futtatott tesztelések során mindkettő elágazás tesztelve lett.

**Comment by benjamingehl** [comment]
Code coverage report: https://github.com/BME-MIT-IET/Hmmm-iet-2018/blob/unit-test/url.js#L229
Az else ág sosem fut le. Jelenleg nem látom, hogyan tudna az egész kifejezés hamis lenni. A getKey() visszatérési értéke mindig string lesz.

**Comment by BMark96** [comment]
Code coverage report: https://github.com/BME-MIT-IET/Hmmm-iet-2018/blob/unit-test/url.js#L308
Az else ág itt se fut le sosem, mivel a query string-ek nem függvény típusúak.

**Comment by daunera** [comment]
Oké, rendben van. Ahogy láttam a plusz eszköz frissebb node-ot igényelt és a travis erre build error-olt, de látom orvosoltátok. Így minden szuper, szép munka, zárom!

**Comment by BMark96** [comment]
Igen, a node verziót 7.6-ra frissítettük, és azzal már probléma nélkül futott a travis build.
